/**
 * Ridgelines generated by midpoint displacement — the same fractal used for
 * terrain height maps, run in one dimension.
 *
 * Hand-drawn curves kept coming out as either a sawtooth or a sine wave; real
 * rock is self-similar, so every subdivision here displaces the midpoint by a
 * random amount that halves with each pass. The result is irregular at every
 * scale: broad massifs, spurs on their flanks, and small broken teeth along the
 * crest.
 *
 * The generator is seeded, so the server and the client draw the same range and
 * hydration doesn't mismatch.
 */

export const RIDGE_BOX = { width: 1440, height: 520 } as const;

/** mulberry32 — small, fast, and deterministic from an integer seed. */
function rng(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * @param seed      picks the range
 * @param depth     2^depth + 1 points across the box
 * @param amplitude starting displacement, in box units
 * @param roughness how fast the displacement decays; lower = smoother, which is
 *                  what distance does to a skyline
 */
function heights(seed: number, depth: number, amplitude: number, roughness: number) {
  const random = rng(seed);
  const count = 2 ** depth + 1;
  const points = new Array<number>(count).fill(0);
  points[0] = (random() - 0.5) * amplitude;
  points[count - 1] = (random() - 0.5) * amplitude;

  for (let step = count - 1; step > 1; step /= 2) {
    const half = step / 2;
    for (let i = half; i < count; i += step) {
      const mid = (points[i - half] + points[i + half]) / 2;
      points[i] = mid + (random() - 0.5) * amplitude;
    }
    amplitude *= roughness;
  }
  return points;
}

function ridgePath(seed: number, baseY: number, amplitude: number, roughness: number, depth = 7) {
  const points = heights(seed, depth, amplitude, roughness);
  const stepX = RIDGE_BOX.width / (points.length - 1);
  const d = points
    .map((h, i) => `${i === 0 ? "M" : "L"} ${(i * stepX).toFixed(1)} ${(baseY + h).toFixed(1)}`)
    .join(" ");
  return `${d} L ${RIDGE_BOX.width} ${RIDGE_BOX.height} L 0 ${RIDGE_BOX.height} Z`;
}

/**
 * Far to near. Distance flattens a skyline, so the far range gets the smallest
 * amplitude and the fastest decay; the near range is tall, rough and close.
 */
export const RIDGE_PATHS = [
  ridgePath(20260917, 250, 190, 0.52),
  ridgePath(884213, 330, 240, 0.56),
  ridgePath(1471902, 424, 300, 0.6),
] as const;
